import type { Metadata } from "next"
import { Footer } from "@/components/footer"
import { Header } from "@/components/header"

export const metadata: Metadata = {
  title: "Terms of Service | Premier Window Care",
  description: "Terms of Service for Premier Window Care.",
}

export default function TermsOfServicePage() {
  return (
    <main>
      <Header />
      <article className="mx-auto max-w-4xl px-4 pb-16 pt-32 text-base leading-7 text-slate-700 md:pb-24 md:pt-40">
        <p className="mb-3 text-sm font-bold uppercase tracking-wide text-blue-primary">Legal</p>
        <h1 className="mb-3 text-4xl font-bold tracking-tight text-blue-deep md:text-5xl">Terms of Service</h1>
        <p className="mb-10 text-sm text-slate-500">Effective date: July 20, 2026</p>

        <div className="space-y-10">
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">1. Acceptance of These Terms</h2><p>These Terms of Service ("Terms") govern your use of https://cleanwithpremier.com (the "Website") and its features. By using the Website, submitting a quote request, or contacting Premier Window Care LLC ("Premier," "we," "us," or "our"), you agree to these Terms. If you do not agree, do not use the Website.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">2. Our Services</h2><p>Premier provides residential and commercial window-cleaning services in West Michigan, including interior and exterior window cleaning, screen cleaning, hard-water removal, maintenance plans, and other services we may offer. Service availability depends on location, conditions, scheduling, scope, and other factors.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">3. Website Use</h2><p>You may use the Website only for lawful purposes. You may not interfere with its operation, attempt unauthorized access, use automated means to extract content or data without permission, submit false or misleading information, transmit malicious code, or use the Website in a way that infringes another person&apos;s rights.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">4. Quotes, Estimates, Pricing, and Availability</h2><p>Website content and any preliminary quote request are informational and do not create a binding agreement, guarantee a price, or reserve an appointment. Quotes and estimates may depend on an assessment of the property, the scope of work, access, window condition, materials, travel, timing, and other relevant factors. Final pricing, scope, scheduling, payment terms, and any service-specific terms will be confirmed separately before service is performed. We may correct errors, update pricing, decline requests, or change availability at any time.</p><p className="mt-3">You may cancel or reschedule an appointment by text message or email before the scheduled service. We may continue working in rain unless you ask us not to. Customers are responsible for providing safe and reasonable access to the service area. Payment must be made using the agreed method, including cash, check, or invoice. Overdue payments will be followed up until paid, and we may take further action when necessary.</p><p className="mt-3">We stand behind every job with our satisfaction guarantee. If you identify dirty windows or service details we missed, we will fix them at no additional charge within reasonable expectations. This guarantee applies to the agreed scope of service and does not require work that is outside that scope or cannot be safely performed.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">5. Maintenance-Plan Benefits</h2><p>Customers enrolled in a Premier maintenance plan may request one complimentary touch-up per month between their scheduled services. Each touch-up is limited to 30 minutes and applies only to the property and services covered by the applicable maintenance plan. Touch-ups are subject to safe access, weather conditions, scheduling availability, and the agreed service scope.</p><p className="mt-3">Maintenance plans include a 7-Day Rain Guarantee: if windows cleaned during a scheduled maintenance visit get dirty within seven days, we will reclean them completely at no additional charge. The guarantee applies to the windows and agreed service scope from that visit and is subject to safe access and scheduling availability.</p><p className="mt-3">Screen cleaning is an optional add-on and is not included with maintenance plans unless it is specifically included in the agreed service scope.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">6. User-Submitted Information</h2><p>You are responsible for information you submit through the Website, including quote-request details. You represent that it is accurate and that you have the right to provide it. You grant us permission to use submitted information as needed to respond to your request, prepare a quote, provide services, and operate our business, consistent with our Privacy Policy.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">7. Intellectual Property</h2><p>The Website and its text, design, logos, photographs, videos, graphics, and other content are owned by or licensed to Premier and are protected by applicable intellectual-property laws. You may not copy, reproduce, distribute, modify, display, or create derivative works from Website content without our prior written permission, except as permitted by law.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">8. Third-Party Services and Links</h2><p>The Website uses or links to third-party services, including Formspree, Tawk.to, Google Maps, Google Analytics, and Vercel Analytics. We do not control third-party websites or services and are not responsible for their content, availability, security, or privacy practices. Your use of them is governed by their applicable terms and privacy notices.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">9. Disclaimer of Warranties</h2><p>To the fullest extent permitted by law, the Website is provided on an "as is" and "as available" basis, without warranties of any kind, whether express, implied, or statutory. We do not warrant that the Website will be uninterrupted, secure, error-free, or free of harmful components, or that Website content will always be accurate or current. Nothing in these Terms limits any warranty that cannot legally be excluded.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">10. Limitation of Liability</h2><p>To the fullest extent permitted by law, Premier and its owners, employees, contractors, and service providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, including loss of profits, data, goodwill, or other intangible losses, arising from or related to your use of or inability to use the Website; unauthorized access to or use of the Website or personal information stored through it; interruption or cessation of transmission to or from the Website; or bugs, viruses, or other harmful code that may be transmitted through the Website.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">11. Indemnification</h2><p>To the fullest extent permitted by law, you agree to defend, indemnify, and hold harmless Premier and its owners, employees, contractors, and service providers from claims, liabilities, damages, losses, and expenses, including reasonable attorneys&apos; fees, arising from your violation of these Terms, your misuse of the Website, or your infringement of another person&apos;s rights.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">12. Governing Law and Venue</h2><p>These Terms are governed by the laws of the State of Michigan, without regard to conflict-of-law rules. Any dispute that is not resolved informally will be brought in a court of competent jurisdiction, and you consent to the jurisdiction of that court.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">13. Changes to These Terms</h2><p>We may revise these Terms from time to time. The revised Terms will be posted on this page with an updated effective date. Your continued use of the Website after changes take effect means you accept the revised Terms.</p></section>
          <section><h2 className="mb-3 text-2xl font-bold text-blue-deep">14. Contact Us</h2><p>For questions about these Terms, contact Premier Window Care LLC at <a className="text-blue-primary underline" href="mailto:info@cleanwithpremier.com">info@cleanwithpremier.com</a>, <a className="text-blue-primary underline" href="tel:6164224749">(616) 422-4749</a>, or 4672 40th Ave, Hudsonville, MI 49426.</p></section>
        </div>
      </article>
      <Footer />
    </main>
  )
}
